// Code generated by Slice Machine. DO NOT EDIT.

import Header from './Header';
import Quote from './Quote';
import Section from './Section';

export {
	Header,
	Quote,
	Section,
};

export const components = {
	header: Header,
	quote: Quote,
	section: Section,
};
